# Generated by Django 5.2.4 on 2025-09-19 08:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0023_remove_category_main_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='Administration.category')),
                ('color_images', models.ManyToManyField(blank=True, related_name='customizations', to='base.customizationcolorimage')),
                ('function_images', models.ManyToManyField(blank=True, related_name='customizations', to='base.customizationfunctionimage')),
                ('packaging_images', models.ManyToManyField(blank=True, related_name='customizations', to='base.customizationpackagingimage')),
                ('texture_images', models.ManyToManyField(blank=True, related_name='customizations', to='base.customizationtextureimage')),
            ],
        ),
        migrations.CreateModel(
            name='HowItworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='how_it_works/')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works', to='Administration.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Administration.maincategory'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Administration.category')),
                ('features', models.ManyToManyField(blank=True, help_text='Key features or benefits', related_name='products', to='base.productfeatures')),
                ('images', models.ManyToManyField(blank=True, related_name='products', to='base.productimage')),
            ],
        ),
    ]
