# Generated by Django 5.2.4 on 2025-09-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_maincategory_image'),
        ('base', '0023_remove_category_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_images',
            field=models.ManyToManyField(blank=True, related_name='product_customizations', to='base.customizationcolorimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_images',
            field=models.ManyToManyField(blank=True, related_name='product_customizations', to='base.customizationpackagingimage'),
        ),
    ]
