# Generated by Django 5.2.4 on 2025-09-10 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('makeup', 'Makeup'), ('skincare', 'Skincare')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True, help_text='List of ingredients')),
                ('min_order_quantity', models.PositiveIntegerField(default=100)),
                ('packaging_options', models.CharField(blank=True, help_text='Bottle, jar, tube, etc.', max_length=255)),
                ('color_options', models.CharField(blank=True, help_text='Available shades/colors', max_length=255)),
                ('fragrance_options', models.CharField(blank=True, help_text='Available fragrances/scents', max_length=255)),
                ('logo_printing', models.BooleanField(default=True, help_text='Allow custom logo printing')),
                ('custom_label', models.BooleanField(default=True, help_text='Allow custom label design')),
                ('box_packaging', models.BooleanField(default=True, help_text='Allow custom box packaging')),
                ('certification_options', models.CharField(blank=True, help_text='E.g. Vegan, Cruelty-Free, etc.', max_length=255)),
                ('sample_available', models.BooleanField(default=True)),
                ('lead_time_days', models.PositiveIntegerField(default=30, help_text='Production lead time in days')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Base price per unit', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='base.category')),
                ('images', models.ManyToManyField(blank=True, related_name='products', to='base.productimage')),
            ],
        ),
    ]
