# Generated by Django 5.2.4 on 2025-09-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorShade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(blank=True, help_text='Optional HEX color code', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='certification_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_options',
        ),
        migrations.AddField(
            model_name='product',
            name='certification_options',
            field=models.ManyToManyField(blank=True, help_text='E.g. Vegan, Cruelty-Free, etc.', related_name='products', to='base.certification'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.ManyToManyField(blank=True, help_text='Available shades/colors', related_name='products', to='base.colorshade'),
        ),
    ]
