# Generated by Django 5.2.4 on 2025-09-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_certification_colorshade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='fragrance_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging_options',
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_options',
            field=models.ManyToManyField(blank=True, help_text='Available fragrances/scents', related_name='products', to='base.fragranceoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_options',
            field=models.ManyToManyField(blank=True, help_text='Bottle, jar, tube, etc.', related_name='products', to='base.packagingoption'),
        ),
    ]
