# Generated by Django 5.2.4 on 2025-09-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_fragranceoption_packagingoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlighted_features',
            field=models.TextField(blank=True, help_text='Key features or benefits'),
        ),
    ]
