# Generated by Django 5.2.4 on 2025-09-11 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_highlighted_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customizations/colors/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationFunctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customizations/functions/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationPackagingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customizations/packaging/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationTextureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customizations/textures/')),
            ],
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='base.category')),
                ('color_images', models.ManyToManyField(blank=True, related_name='customizations', to='base.customizationcolorimage')),
                ('function_images', models.ManyToManyField(blank=True, related_name='customizations', to='base.customizationfunctionimage')),
                ('packaging_images', models.ManyToManyField(blank=True, related_name='customizations', to='base.customizationpackagingimage')),
                ('texture_images', models.ManyToManyField(blank=True, related_name='customizations', to='base.customizationtextureimage')),
            ],
        ),
    ]
