# Generated by Django 5.2.4 on 2025-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customizationcolorimage_customizationfunctionimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price per unit', max_digits=10),
        ),
    ]
