# Generated by Django 5.2.4 on 2025-09-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_price_per_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification',
            new_name='Functions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='certification_options',
            new_name='function_options',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price per unit', max_digits=10, null=True),
        ),
    ]
