# Generated by Django 5.2.4 on 2025-09-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_certification_functions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sample_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
