# Generated by Django 5.2.4 on 2025-09-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_product_lead_time_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fragrance_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='function_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='logo_printing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
