# Generated by Django 5.2.4 on 2025-09-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_product_custom_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorshade',
            name='hex_code',
        ),
        migrations.AddField(
            model_name='colorshade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/colors/'),
        ),
        migrations.AddField(
            model_name='packagingoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/packaging/'),
        ),
    ]
