# Generated by Django 5.2.4 on 2025-09-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_colorshade_hex_code_colorshade_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_packaging',
        ),
    ]
