# Generated by Django 5.2.4 on 2025-09-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='User uploaded spec/artwork/details file', null=True, upload_to='quote_uploads/'),
        ),
    ]
