# Generated by Django 5.2.4 on 2025-09-16 12:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_quoterequest_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlighted_features',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Key features or benefits'),
        ),
    ]
