# Generated by Django 5.2.4 on 2025-09-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlighted_features',
        ),
        migrations.AddField(
            model_name='product',
            name='function_options',
            field=models.ManyToManyField(blank=True, help_text='E.g. Vegan, Cruelty-Free, etc.', related_name='products', to='base.functions'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Key features or benefits', related_name='products', to='base.productfeatures'),
        ),
    ]
