# Generated by Django 5.2.4 on 2025-09-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_productfeatures_remove_product_highlighted_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='function_options',
        ),
    ]
