# Generated by Django 5.2.4 on 2025-09-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_product_function_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='how_it_works/')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works', to='base.category')),
            ],
        ),
    ]
