# Generated by Django 5.2.4 on 2025-09-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_howitworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
    ]
