# Generated by Django 5.2.4 on 2025-09-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='custom_color_image',
            field=models.ImageField(blank=True, help_text='User uploaded custom color image', null=True, upload_to='quote_uploads/custom_colors/'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='custom_packaging_image',
            field=models.ImageField(blank=True, help_text='User uploaded custom packaging image', null=True, upload_to='quote_uploads/custom_packaging/'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='spec_sheet_file',
            field=models.FileField(blank=True, help_text='User uploaded spec/artwork/details file', null=True, upload_to='quote_uploads/spec_sheets/'),
        ),
    ]
