# Generated by Django 5.2.4 on 2025-09-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_quoterequest_uploaded_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FragranceOption',
        ),
        migrations.DeleteModel(
            name='Functions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_options',
        ),
        migrations.DeleteModel(
            name='PackagingOption',
        ),
    ]
