# Generated by Django 5.2.4 on 2025-09-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_maincategory_remove_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='category',
        ),
        migrations.RemoveField(
            model_name='howitworks',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='color_images',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='function_images',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='packaging_images',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='texture_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='HowItworks',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
