# Generated by Django 5.2.7 on 2025-10-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_quoteattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteattachment',
            name='wishlist_item_id',
            field=models.CharField(blank=True, help_text='Unique wishlist item id (from localStorage)', max_length=100, null=True),
        ),
    ]
